services:
  - type: web
    name: fb-group-poster
    env: node
    buildCommand: npm ci --include=dev && npm run build
    startCommand: npm start
    disk:
      name: paste-happy-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
