import { useCallback, useEffect, useMemo, useState } from 'react';
import { ParsedCsvRow } from '../lib/csv';

type Status = 'pending' | 'processing' | 'posted' | 'failed' | 'blocked' | 'uncertain' | 'skipped';
interface Job { id: string; groupName: string; groupUrl: string; postText: string; status: Status; attempts: number; lastError: string | null; }
interface WorkerStatus { state: string; currentJob: Job | null; currentStep: string; lastError: string | null; browser: { profileExists: boolean; open: boolean }; }
const blankStatus: WorkerStatus = { state: 'offline', currentJob: null, currentStep: 'Backend unavailable', lastError: null, browser: { profileExists: false, open: false } };

export function AutomationDashboard({ rows }: { rows: ParsedCsvRow[] }) {
  const [jobs, setJobs] = useState<Job[]>([]); const [status, setStatus] = useState(blankStatus); const [error, setError] = useState('');
  const [settings, setSettings] = useState({ delayMs: 15000, cooldownMs: 0, maxJobs: 10, stopOnFailure: false, stopOnCheckpoint: true });
  const refresh = useCallback(async () => {
    try { const [queue, state] = await Promise.all([api('/api/queue'), api('/api/status')]); setJobs(queue); setStatus(state); setError(''); }
    catch { setError('Automatic posting backend is offline. Start it with npm start; manual tools still work.'); }
  }, []);
  useEffect(() => { refresh(); const timer = window.setInterval(refresh, 2000); return () => clearInterval(timer); }, [refresh]);
  const counts = useMemo(() => Object.fromEntries(['pending', 'processing', 'posted', 'failed', 'blocked', 'uncertain'].map((key) => [key, jobs.filter((job) => job.status === key).length])), [jobs]);
  const command = async (path: string, body: unknown = {}) => { try { await api(path, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); await refresh(); } catch (e) { setError((e as Error).message); } };
  const queueRows = () => command('/api/queue/import', { rows: rows.map((row) => ({ groupName: row.name, groupUrl: row.url, postText: row.ad })) });
  return <section className="space-y-4 rounded-3xl border border-violet-500/30 bg-slate-950/80 p-5 shadow-xl">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-violet-300">Playwright automation</p><h2 className="text-2xl font-semibold">Posting queue</h2><p className="text-sm text-slate-400">Browser profile: {status.browser.open ? 'open' : status.browser.profileExists ? 'saved' : 'not created'} · Worker: {status.state}</p></div>
      <div className="flex flex-wrap gap-2"><Button label="Queue for Automatic Posting" onClick={queueRows} disabled={!rows.length}/><Button label="Open Browser / Login" onClick={() => command('/api/browser/login')} /></div></div>
    {error && <p className="rounded-xl border border-amber-500/40 bg-amber-500/10 p-3 text-sm text-amber-100">{error}</p>}
    <div className="grid grid-cols-2 gap-2 sm:grid-cols-4 lg:grid-cols-7"><Metric label="Total" value={jobs.length}/>{Object.entries(counts).map(([key, value]) => <Metric key={key} label={key} value={value}/>)}</div>
    <div className="grid gap-3 rounded-2xl border border-slate-800 bg-slate-900/60 p-4 sm:grid-cols-3"><Field label="Delay between jobs (seconds)" value={settings.delayMs / 1000} onChange={(v) => setSettings({ ...settings, delayMs: v * 1000 })}/><Field label="Cooldown (seconds)" value={settings.cooldownMs / 1000} onChange={(v) => setSettings({ ...settings, cooldownMs: v * 1000 })}/><Field label="Maximum jobs" value={settings.maxJobs} onChange={(v) => setSettings({ ...settings, maxJobs: v })}/>
      <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={settings.stopOnFailure} onChange={(e) => setSettings({ ...settings, stopOnFailure: e.target.checked })}/> Stop on failure</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={settings.stopOnCheckpoint} onChange={(e) => setSettings({ ...settings, stopOnCheckpoint: e.target.checked })}/> Stop on security checkpoint</label></div>
    <div className="flex flex-wrap gap-2"><Button label="Start" onClick={() => command('/api/queue/start', settings)}/><Button label="Pause" onClick={() => command('/api/queue/pause')}/><Button label="Resume" onClick={() => command('/api/queue/resume')}/><Button label="Stop" onClick={() => command('/api/queue/stop')}/></div>
    <div className="rounded-2xl border border-slate-800 p-4 text-sm"><h3 className="font-semibold text-white">Current job</h3><dl className="mt-2 grid gap-1 sm:grid-cols-2"><div>Current Group: {status.currentJob?.groupName || 'None'}</div><div>Current Status: {status.currentJob?.status || status.state}</div><div>Current Step: {status.currentStep}</div><div>Last Error: {status.lastError || 'None'}</div></dl></div>
    <div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="text-xs uppercase text-slate-400"><tr><th className="p-2">Group</th><th className="p-2">Post preview</th><th className="p-2">Status</th><th className="p-2">Attempts</th><th className="p-2">Last error</th><th className="p-2">Actions</th></tr></thead><tbody>{jobs.map((job) => <tr key={job.id} className="border-t border-slate-800"><td className="p-2 font-medium">{job.groupName}</td><td className="max-w-xs truncate p-2">{job.postText}</td><td className="p-2"><span className={`status-${job.status} rounded-full px-2 py-1 text-xs font-bold`}>{job.status}</span></td><td className="p-2">{job.attempts}</td><td className="max-w-xs truncate p-2 text-rose-300" title={job.lastError || ''}>{job.lastError || '—'}</td><td className="p-2"><div className="flex gap-2"><a href={job.groupUrl} target="_blank" rel="noreferrer">Open Group</a>{['failed','blocked','uncertain','skipped'].includes(job.status) && <button className="text-sky-300" onClick={() => command(`/api/queue/${job.id}/retry`)}>Retry</button>}{!['posted','skipped'].includes(job.status) && <button className="text-amber-300" onClick={() => command(`/api/queue/${job.id}/skip`)}>Skip</button>}</div></td></tr>)}</tbody></table>{!jobs.length && <p className="p-4 text-sm text-slate-400">Import your CSV above, then queue its rows here.</p>}</div>
  </section>;
}
async function api(path: string, init?: RequestInit) { const response = await fetch(path, init); const data = await response.json(); if (!response.ok) throw new Error(data.error || `Request failed (${response.status})`); return data; }
function Button({ label, onClick, disabled }: { label: string; onClick: () => void; disabled?: boolean }) { return <button type="button" disabled={disabled} onClick={onClick} className="min-h-11 rounded-full border border-violet-400/50 bg-violet-500/20 px-4 text-sm font-semibold text-violet-50 disabled:opacity-40">{label}</button>; }
function Metric({ label, value }: { label: string; value: number }) { return <div className="rounded-xl bg-slate-900 p-3"><p className="text-xs capitalize text-slate-400">{label}</p><p className="text-xl font-bold">{value}</p></div>; }
function Field({ label, value, onChange }: { label: string; value: number; onChange: (value: number) => void }) { return <label className="text-xs text-slate-400">{label}<input type="number" min="0" value={value} onChange={(e) => onChange(Number(e.target.value))} className="mt-1 h-10 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 text-white"/></label>; }
